// Comprehensive Cab Fleet Categories, Realistic Drivers Database, Offers, and Services
// Designed for South Indian & Pan-Indian Routes

export const CAB_CATEGORIES = [
  {
    id: 'MINI',
    name: 'Mini',
    displayName: 'Mini Hatchback',
    tagline: 'Pocket-friendly city rides',
    sampleModels: 'Maruti WagonR, Tata Tiago, Hyundai Grand i10',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=600&q=80',
    seats: 4,
    luggage: 1,
    ac: true,
    baseFare: 120,
    perKmRate: 11.5,
    minKm: 5,
    etaMinutes: 4,
    features: ['Air Conditioned', 'Compact & Fast', 'Pocket Friendly', 'Daily Commute']
  },
  {
    id: 'SEDAN',
    name: 'Sedan',
    displayName: 'Comfort Sedan',
    tagline: 'Comfortable daily & outstation rides',
    sampleModels: 'Toyota Etios, Maruti Dzire, Honda Amaze, Hyundai Aura',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
    seats: 4,
    luggage: 2,
    ac: true,
    baseFare: 160,
    perKmRate: 14.0,
    minKm: 5,
    etaMinutes: 5,
    features: ['Spacious Boot', 'AC Comfort', 'Top Rated Chauffeurs', 'Smoothest Ride']
  },
  {
    id: 'SUV',
    name: 'SUV',
    displayName: 'Prime SUV',
    tagline: 'Extra legroom & great road clearance',
    sampleModels: 'Hyundai Creta, Kia Seltos, Mahindra Scorpio, Maruti Grand Vitara',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
    seats: 5,
    luggage: 3,
    ac: true,
    baseFare: 220,
    perKmRate: 18.0,
    minKm: 10,
    etaMinutes: 7,
    features: ['High Seating Position', 'Extra Luggage', 'Highway Ready', 'Family Friendly']
  },
  {
    id: 'XL',
    name: 'XL',
    displayName: 'Multi-Utility XL (6+1)',
    tagline: 'Spacious 6-7 seaters for groups & big families',
    sampleModels: 'Toyota Innova Crysta, Maruti Ertiga, Mahindra XUV700',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
    seats: 7,
    luggage: 4,
    ac: true,
    baseFare: 300,
    perKmRate: 22.0,
    minKm: 10,
    etaMinutes: 8,
    features: ['7 Seater Capacity', 'Massive Boot Space', 'Captain Seats Available', 'Interstate Comfort']
  },
  {
    id: 'PREMIUM',
    name: 'Premium',
    displayName: 'Executive Premium',
    tagline: 'Upscale sedans for executive travel',
    sampleModels: 'Toyota Camry, Skoda Octavia, Honda City ZX',
    image: 'https://images.unsplash.com/photo-1555353540-64580b51c258?auto=format&fit=crop&w=600&q=80',
    seats: 4,
    luggage: 3,
    ac: true,
    baseFare: 380,
    perKmRate: 26.0,
    minKm: 10,
    etaMinutes: 9,
    features: ['Leather Upholstery', 'Quiet Cabin', 'Complimentary Water', 'Top 1% Chauffeurs']
  },
  {
    id: 'LUXURY',
    name: 'Luxury',
    displayName: 'Ultra Luxury Chauffeur',
    tagline: 'VIP treatment in world-class German luxury cars',
    sampleModels: 'Mercedes-Benz E-Class, BMW 5 Series, Audi A6',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=600&q=80',
    seats: 4,
    luggage: 3,
    ac: true,
    baseFare: 800,
    perKmRate: 48.0,
    minKm: 15,
    etaMinutes: 12,
    features: ['Mercedes / BMW / Audi', 'White Glove Service', 'Sanitized VIP Cabins', 'Airport Meet & Greet']
  },
  {
    id: 'ELECTRIC',
    name: 'Electric',
    displayName: 'Green EV Cab',
    tagline: 'Eco-friendly 100% electric rides with zero emission',
    sampleModels: 'Tata Nexon EV, MG ZS EV, Hyundai Ioniq 5, BYD Atto 3',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    seats: 4,
    luggage: 2,
    ac: true,
    baseFare: 150,
    perKmRate: 13.5,
    minKm: 5,
    etaMinutes: 5,
    features: ['100% Electric EV', 'Zero Carbon Footprint', 'Silent Smooth Ride', 'Sustainable Travel']
  },
  {
    id: 'OUTSTATION',
    name: 'Outstation',
    displayName: 'Intercity Outstation',
    tagline: 'One-way and round-trip highway transit packages',
    sampleModels: 'Toyota Etios / Ertiga / Innova Crysta',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=600&q=80',
    seats: 6,
    luggage: 4,
    ac: true,
    baseFare: 450,
    perKmRate: 15.5,
    minKm: 50,
    etaMinutes: 10,
    features: ['Highway Specialists', 'Flexible Breaks', 'Toll Transparent', 'No Return Fare Surcharge']
  },
  {
    id: 'AIRPORT',
    name: 'Airport Cab',
    displayName: 'Airport Express Transfer',
    tagline: 'Flight-timed pickups with luggage assistance',
    sampleModels: 'Maruti Dzire / Ertiga / Innova Crysta',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=600&q=80',
    seats: 4,
    luggage: 3,
    ac: true,
    baseFare: 280,
    perKmRate: 16.0,
    minKm: 15,
    etaMinutes: 6,
    features: ['Flight Tracking Buffer', 'Free 45-Min Waiting', 'Terminal Pickup', 'Luggage Assistance']
  },
  {
    id: 'LOCAL',
    name: 'Local Cab',
    displayName: 'City Hourly Rental',
    tagline: 'Cab at your disposal for multiple stops and shopping',
    sampleModels: 'Hyundai Aura / Tata Tiago / Maruti Dzire',
    image: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=600&q=80',
    seats: 4,
    luggage: 2,
    ac: true,
    baseFare: 250,
    perKmRate: 14.0,
    minKm: 10,
    etaMinutes: 5,
    features: ['Unlimited Stops', 'Hourly Packages', 'No Repeated Booking', 'Driver on Call']
  }
];

// Initial Realistic Fleet of 24 Verified Drivers with live availability states
export const INITIAL_DRIVERS = [
  {
    id: 'drv-101',
    name: 'Arun Kumar',
    rating: 4.85,
    trips: 1450,
    experience: '7 years',
    phone: '+91 98401 23456',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Toyota Etios',
    vehicleNumber: 'TN 01 AB 8842',
    category: 'SEDAN',
    ac: true,
    seats: 4,
    luggage: 2,
    fuelType: 'Diesel',
    color: 'Silver Metallic',
    distanceKm: 1.8,
    etaMinutes: 5,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-102',
    name: 'Rajesh Sharma',
    rating: 4.9,
    trips: 2180,
    experience: '9 years',
    phone: '+91 98840 91823',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Maruti Suzuki Dzire',
    vehicleNumber: 'TN 09 CQ 4519',
    category: 'SEDAN',
    ac: true,
    seats: 4,
    luggage: 2,
    fuelType: 'CNG / Petrol',
    color: 'Pearl White',
    distanceKm: 2.3,
    etaMinutes: 6,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'Hindi', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-103',
    name: 'Priya Sundaram',
    rating: 4.95,
    trips: 1840,
    experience: '6 years',
    phone: '+91 94441 77209',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Tata Nexon EV Max',
    vehicleNumber: 'TN 07 EV 3042',
    category: 'ELECTRIC',
    ac: true,
    seats: 4,
    luggage: 2,
    fuelType: '100% Electric',
    color: 'Teal Blue',
    distanceKm: 1.2,
    etaMinutes: 4,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-104',
    name: 'Karthik Raj',
    rating: 4.8,
    trips: 3200,
    experience: '11 years',
    phone: '+91 97908 44120',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Toyota Innova Crysta ZX',
    vehicleNumber: 'TN 14 AX 9001',
    category: 'XL',
    ac: true,
    seats: 7,
    luggage: 4,
    fuelType: 'Diesel',
    color: 'Super White',
    distanceKm: 3.1,
    etaMinutes: 8,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'Telugu', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-105',
    name: 'Mohammed Farooq',
    rating: 4.75,
    trips: 1120,
    experience: '5 years',
    phone: '+91 98841 55902',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Hyundai Creta SX(O)',
    vehicleNumber: 'TN 22 BN 1098',
    category: 'SUV',
    ac: true,
    seats: 5,
    luggage: 3,
    fuelType: 'Diesel',
    color: 'Phantom Black',
    distanceKm: 2.7,
    etaMinutes: 7,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'Urdu', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-106',
    name: 'Suresh Babu',
    rating: 4.7,
    trips: 940,
    experience: '4 years',
    phone: '+91 97102 33491',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Maruti WagonR VXI',
    vehicleNumber: 'TN 02 DB 6721',
    category: 'MINI',
    ac: true,
    seats: 4,
    luggage: 1,
    fuelType: 'CNG',
    color: 'Magma Grey',
    distanceKm: 0.9,
    etaMinutes: 3,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-107',
    name: 'Vikram Prabhu',
    rating: 4.92,
    trips: 1650,
    experience: '8 years',
    phone: '+91 99620 44810',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Mercedes-Benz E-Class E220d',
    vehicleNumber: 'TN 09 VIP 0007',
    category: 'LUXURY',
    ac: true,
    seats: 4,
    luggage: 3,
    fuelType: 'Diesel',
    color: 'Obsidian Black',
    distanceKm: 4.2,
    etaMinutes: 11,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English', 'Hindi'],
    vehicleImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-108',
    name: 'Deepa Nair',
    rating: 4.88,
    trips: 1390,
    experience: '6 years',
    phone: '+91 94470 12894',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Honda City ZX VTEC',
    vehicleNumber: 'TN 10 DX 8192',
    category: 'PREMIUM',
    ac: true,
    seats: 4,
    luggage: 3,
    fuelType: 'Petrol',
    color: 'Radiant Red',
    distanceKm: 2.9,
    etaMinutes: 7,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'Malayalam', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1555353540-64580b51c258?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-109',
    name: 'Anand Venkatesh',
    rating: 4.82,
    trips: 2750,
    experience: '10 years',
    phone: '+91 98410 88219',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Toyota Innova Hycross',
    vehicleNumber: 'TN 07 EX 4421',
    category: 'OUTSTATION',
    ac: true,
    seats: 7,
    luggage: 4,
    fuelType: 'Hybrid Petrol',
    color: 'Attitude Black',
    distanceKm: 3.8,
    etaMinutes: 9,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'Kannada', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-110',
    name: 'Vignesh Krishnan',
    rating: 4.86,
    trips: 1540,
    experience: '7 years',
    phone: '+91 98845 77123',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Maruti Suzuki Ertiga ZXI+',
    vehicleNumber: 'TN 04 CA 3381',
    category: 'AIRPORT',
    ac: true,
    seats: 6,
    luggage: 3,
    fuelType: 'CNG',
    color: 'Oxford Blue',
    distanceKm: 1.5,
    etaMinutes: 4,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-111',
    name: 'Manoj Kumar',
    rating: 4.78,
    trips: 870,
    experience: '4 years',
    phone: '+91 98402 11983',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Hyundai Aura SX',
    vehicleNumber: 'TN 05 BM 7810',
    category: 'LOCAL',
    ac: true,
    seats: 4,
    luggage: 2,
    fuelType: 'Petrol',
    color: 'Titan Grey',
    distanceKm: 1.1,
    etaMinutes: 3,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'Telugu'],
    vehicleImage: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-112',
    name: 'Naveen Prakash',
    rating: 4.91,
    trips: 2430,
    experience: '8 years',
    phone: '+91 99401 66320',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'MG ZS EV Exclusive',
    vehicleNumber: 'TN 19 EV 1180',
    category: 'ELECTRIC',
    ac: true,
    seats: 4,
    luggage: 2,
    fuelType: '100% Electric',
    color: 'Aurora Silver',
    distanceKm: 2.1,
    etaMinutes: 5,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English', 'Hindi'],
    vehicleImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-113',
    name: 'Ramesh Chandran',
    rating: 4.84,
    trips: 1890,
    experience: '8 years',
    phone: '+91 98842 99014',
    avatar: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Kia Seltos HTX',
    vehicleNumber: 'TN 01 DA 5612',
    category: 'SUV',
    ac: true,
    seats: 5,
    luggage: 3,
    fuelType: 'Diesel',
    color: 'Gravity Grey',
    distanceKm: 2.5,
    etaMinutes: 6,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-114',
    name: 'Balaji Natarajan',
    rating: 4.93,
    trips: 3410,
    experience: '12 years',
    phone: '+91 97100 45891',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'BMW 5 Series 520d Luxury Line',
    vehicleNumber: 'TN 09 VIP 9999',
    category: 'LUXURY',
    ac: true,
    seats: 4,
    luggage: 3,
    fuelType: 'Diesel',
    color: 'Imperial Blue',
    distanceKm: 3.5,
    etaMinutes: 9,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English', 'Hindi', 'French'],
    vehicleImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-115',
    name: 'Gowtham Sethupathi',
    rating: 4.79,
    trips: 1210,
    experience: '5 years',
    phone: '+91 94440 88319',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Tata Tiago XZA',
    vehicleNumber: 'TN 11 AC 9012',
    category: 'MINI',
    ac: true,
    seats: 4,
    luggage: 1,
    fuelType: 'Petrol',
    color: 'Flame Red',
    distanceKm: 1.6,
    etaMinutes: 4,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'drv-116',
    name: 'Kishore Varman',
    rating: 4.87,
    trips: 2050,
    experience: '9 years',
    phone: '+91 98409 33177',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    vehicleModel: 'Skoda Octavia L&K',
    vehicleNumber: 'TN 02 BX 7701',
    category: 'PREMIUM',
    ac: true,
    seats: 4,
    luggage: 3,
    fuelType: 'Petrol',
    color: 'Candy White',
    distanceKm: 3.0,
    etaMinutes: 8,
    available: true,
    city: 'Chennai',
    languages: ['Tamil', 'English'],
    vehicleImage: 'https://images.unsplash.com/photo-1555353540-64580b51c258?auto=format&fit=crop&w=600&q=80',
  }
];

// Active Working Coupons
export const CAB_OFFERS = [
  {
    code: 'CAB50',
    title: 'Flat ₹50 OFF',
    desc: 'Instant discount on any city or local cab ride.',
    discount: 50,
    isPercent: false,
    minFare: 200,
    color: '#DC2626',
    badge: 'Popular'
  },
  {
    code: 'FIRSTCAB',
    title: 'Flat ₹100 OFF',
    desc: 'Welcome offer on your very first cab booking.',
    discount: 100,
    isPercent: false,
    minFare: 300,
    color: '#059669',
    badge: 'New User'
  },
  {
    code: 'AIRPORT20',
    title: '20% OFF Airport Rides',
    desc: 'Save up to ₹250 on scheduled airport transfers.',
    discount: 20,
    isPercent: true,
    maxDiscount: 250,
    minFare: 400,
    color: '#D97706',
    badge: 'Airport'
  },
  {
    code: 'OUTSTATION15',
    title: '15% OFF Outstation',
    desc: 'Save up to ₹500 on all interstate & outstation routes.',
    discount: 15,
    isPercent: true,
    maxDiscount: 500,
    minFare: 1200,
    color: '#781D2D',
    badge: 'Long Drive'
  },
  {
    code: 'WEEKEND10',
    title: 'Flat 10% Weekend Deal',
    desc: 'Extra savings for Friday to Sunday family rides.',
    discount: 10,
    isPercent: true,
    maxDiscount: 200,
    minFare: 350,
    color: '#E11D48',
    badge: 'Weekend'
  },
  {
    code: 'GREENEV50',
    title: '₹75 OFF Electric Cabs',
    desc: 'Special incentive for booking eco-friendly Green EV cabs.',
    discount: 75,
    isPercent: false,
    minFare: 250,
    color: '#10B981',
    badge: 'Eco Friendly'
  }
];

// 8 Cab Services
export const CAB_SERVICES = [
  {
    id: 'local',
    title: 'Local Ride',
    icon: '🚕',
    desc: 'Point-to-point quick city transit at zero surge pricing.',
    category: 'SEDAN'
  },
  {
    id: 'airport',
    title: 'Airport Transfer',
    icon: '✈️',
    desc: 'Guaranteed on-time terminal pickups with flight buffer.',
    category: 'AIRPORT'
  },
  {
    id: 'outstation',
    title: 'Outstation',
    icon: '🛣️',
    desc: 'One-way and round trips with verified highway chauffeurs.',
    category: 'OUTSTATION'
  },
  {
    id: 'city',
    title: 'City Ride',
    icon: '🏙️',
    desc: 'Everyday commuting in comfortable AC hatchbacks & sedans.',
    category: 'MINI'
  },
  {
    id: 'family',
    title: 'Family Ride',
    icon: '👨‍👩‍👧',
    desc: 'Spacious 6-7 seaters (Innova / Ertiga) with extra boot space.',
    category: 'XL'
  },
  {
    id: 'business',
    title: 'Business Ride',
    icon: '💼',
    desc: 'Executive class sedans with Wi-Fi and mobile charging.',
    category: 'PREMIUM'
  },
  {
    id: 'night',
    title: 'Night Ride',
    icon: '🌙',
    desc: 'Safe, GPS-monitored late night rides with 24/7 SOS helpline.',
    category: 'SEDAN'
  },
  {
    id: 'electric',
    title: 'Electric Cab',
    icon: '⚡',
    desc: '100% silent, eco-friendly EV rides for zero-emission travel.',
    category: 'ELECTRIC'
  }
];

// Cab Booking FAQs
export const CAB_FAQS = [
  {
    q: 'How does the Cab Booking system calculate the fare?',
    a: 'Cab fares are calculated transparently based on actual driving distance, the chosen vehicle category (Mini, Sedan, SUV, XL, Luxury, EV), base fare, estimated toll charges, night surcharges (if applicable between 10 PM and 5 AM), and any active discount coupon applied.'
  },
  {
    q: 'How do I know if my assigned driver is available and confirmed?',
    a: 'We only show live, verified drivers whose availability status is strictly Available. Once you complete the booking, that driver is immediately reserved exclusively for your ride and will arrive at your pickup location with live GPS tracking.'
  },
  {
    q: 'Can I cancel my cab booking and receive a refund?',
    a: 'Yes, cancellations are hassle-free! You can cancel your cab booking from the Confirmation page or the My Cab Bookings dashboard. Once cancelled, your refund is processed immediately, and the driver is released back to the available pool.'
  },
  {
    q: 'How do I track my cab in real-time?',
    a: 'Once your cab is confirmed, click the "Track Cab" button to view your interactive live map. You can monitor driver location, speed, route progression, and estimated arrival countdown.'
  },
  {
    q: 'Are tolls and parking charges included in the fare?',
    a: 'Estimated state and national highway tolls are calculated and displayed transparently in your fare breakdown before you pay. No surprise hidden charges at the end of the trip!'
  },
  {
    q: 'What amenities are provided in NextBus cabs?',
    a: 'All our cabs feature clean Air Conditioning, mobile USB fast-charging ports, sanitized seating, complimentary bottled water (in Premium/Luxury categories), and 24/7 GPS safety tracking with emergency SOS support.'
  }
];
